util/data_format/np.load line 38

data = something with the pdb file


if pdb = true:

    run
    
else:

    Do something else

In [1]:
import pandas as pd
import numpy as np
import zipfile
from biopandas.mol2 import PandasMol2

In [2]:
from biopandas.pdb import PandasPdb
from zipfile import ZipFile
ppdb=PandasPdb().fetch_pdb('3eiy')

In [3]:
ppdb

In [46]:
openf=ppdb.read_pdb('1a00B00')

In [50]:
def load_pdb(file):
    opene=ppdb.read_pdb(file)
    return opene

In [51]:
load_pdb('1a00B00')

In [6]:
openf

In [11]:
openf.df['ATOM'].head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
0        ATOM         1071                 N                  MET           
1        ATOM         1072                CA                  MET           
2        ATOM         1073                 C                  MET           
3        ATOM         1074                 O                  MET           
4        ATOM         1075                CB                  MET           

  chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
0        B               1            ...  68.023   46.313   -6.831   
1        B               1            ...  68.102   45.947   -8.262   
2        B               1            ...  66.983   46.661   -9.019   
3        B               1            ...  65.871   46.161   -9.257   
4        B               1            ...  68.038   44.451   -8.471   

   occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
0        1.0     68.69                                       NaN         0  
1        1.0     66.01                                       NaN         1  
2        1.0     62.47                                       NaN         2  
3        1.0     63.00                                       NaN         3  
4        1.0     68.03                                       NaN         4  

[5 rows x 21 columns]

In [14]:
atom_numbers=openf.df['ATOM']['atom_number'].values

In [15]:
atom_numbers

array([1071, 1072, 1073, ..., 2190, 2191, 2192])

In [16]:
residue_names=openf.df['ATOM']['residue_name'].values

In [17]:
residue_names

array(['MET', 'MET', 'MET', ..., 'HIS', 'HIS', 'HIS'], dtype=object)

In [18]:
atom_types=openf.df['ATOM']['atom_name']

In [38]:
c1_x = []
c2_x = []
c3_x = []

In [39]:
c1 = openf.df['ATOM']['x_coord'].values.tolist()
c2 = openf.df['ATOM']['y_coord'].values.tolist()
c3 = openf.df['ATOM']['z_coord'].values.tolist()
c1_x.append(c1)
c2_x.append(c2)
c3_x.append(c3)

In [41]:
atm_lst
for i in range(len(c1_x)):
    for j in range(len(c1_x[i])):
        ls = [c1_x[i][j], c2_x[i][j], c3_x[i][j]]
        atm_lst.append(ls)
    

In [44]:
len(atm_lst)

1122

In [45]:
len(xcoord)

1122

In [35]:
atm_lst=[]
for i in range(len(xcoord)):
    for j in range(len(xcoord[i])):
        ls = [xcoord[i][j], ycoord[i][j], zcoord[i][j]]
        atm_lst.append(ls)

TypeError: object of type 'float' has no len()

In [37]:
range(len(xcoord))

range(0, 1122)

In [26]:
coords=[xcoord, ycoord, zcoord]

In [28]:
coords

[array([68.023, 68.102, 66.983, ..., 69.044, 68.927, 71.053]),
 array([46.313, 45.947, 46.661, ..., 25.193, 25.647, 28.461]),
 array([-6.831, -8.262, -9.019, ...,  5.706,  4.472,  8.379])]